name: Deploy en AWS Lightsail

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Ajusta según la versión necesaria

      - name: Install dependencies
        run: |
          npm install

      - name: Build React app
        run: |
          npm run build

      - name: Conexion SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Agregar host a known_hosts
        run: |
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        env:
          HOST: 18.216.2.88

      - name: Transferir archivos de build a Lightsail
        env:
          HOST: 18.216.2.88
          USER: ubuntu
        run: |
          rsync -avz --delete build/ $USER@$HOST:/var/www/html/

      - name: Reiniciar servidor (opcional)
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.216.2.88 << 'EOF'
          # Reiniciar el servidor si es necesario
          # sudo systemctl restart apache2
          EOF
