name: Deploy en AWS Lightsail

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Conexion SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Despliegue en Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.216.2.88 << 'EOF'
          
          # Navegar al directorio de trabajo
          cd /var/www/html
          
          # Si el directorio es un repositorio git, hacer pull
          if [ -d ".git" ]; then
              echo "Repositorio encontrado, realizando git pull..."
              git pull origin main
          else
              # Si no es un repositorio git, clonar el repositorio
              echo "Repositorio no encontrado, clonando..."
              git clone https://github.com/Practicas-PS/QR_Generator.git .
          fi
          
          # Instalar dependencias
          echo "Instalando dependencias..."
          npm install
          
          # Realizar build del proyecto
          echo "Realizando build..."
          npm run build
          
          # Instalar y configurar Nginx
          echo "Instalando Nginx..."
          sudo apt update
          sudo apt install -y nginx
          
          # Eliminar configuración anterior de Nginx si existe
          sudo rm -f /etc/nginx/sites-enabled/mi_aplicacion
          sudo rm -f /etc/nginx/sites-available/mi_aplicacion
          
          # Configuración de Nginx para servir la aplicación React
          echo "Configurando Nginx..."
          sudo bash -c 'cat > /etc/nginx/sites-available/mi_aplicacion <<EOF
          server {
              listen 80;
              server_name 18.216.2.88;  # O tu IP pública
              root /var/www/html/build;  # Carpeta donde se encuentra el build
              index index.html;
          
              location / {
                  try_files \$uri \$uri/ /index.html;  # Asegura que se sirvan archivos estáticos correctamente
              }
              
              # Evitar la visualización de directorios
              autoindex off;  # Desactiva el listado de directorios
          }
          EOF'
          
          # Habilitar la configuración de Nginx
          sudo ln -s /etc/nginx/sites-available/mi_aplicacion /etc/nginx/sites-enabled/
          
          # Probar la configuración de Nginx
          sudo nginx -t
          
          # Reiniciar Nginx para aplicar la configuración
          sudo systemctl restart nginx || (echo "Error al reiniciar Nginx" && exit 1)
          
          EOF
