name: Deploy en AWS Lightsail

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout del código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Ajustar según la versión necesaria

      # Instalar dependencias
      - name: Install dependencies
        run: |
          npm install

      # Construir la aplicación React
      - name: Build React app
        run: |
          npm run build

      # Configurar la conexión SSH
      - name: Conexion SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Agregar host a known_hosts
      - name: Agregar host a known_hosts
        run: |
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        env:
          HOST: 18.216.2.88

      # Transferir archivos de build a Lightsail
      - name: Transferir archivos de build a Lightsail
        env:
          HOST: 18.216.2.88
          USER: ubuntu
        run: |
          rsync -avz --delete build/ $USER@$HOST:/var/www/html/

      # Despliegue en Lightsail (clonación o actualización del repositorio)
      - name: Despliegue en Lightsail
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.216.2.88 << 'EOF'
          cd /var/www/html

          # Verificar si el directorio es un repositorio git
          if [ ! -d ".git" ]; then
              echo "Eliminando contenido previo..."
              rm -rf *
              echo "Clonando repositorio..."
              git clone https://github.com/Practicas-PS/QR_Generator.git .
          else
              echo "Repositorio encontrado, realizando git pull..."
              git pull origin main
          fi

          # Instalar dependencias si package.json está presente
          if [ -f "package.json" ]; then
              npm install
              npm run build
          else
              echo "Error: package.json no encontrado. Verifique que el repositorio contenga este archivo."
              exit 1
          fi

          # (Opcional) Reiniciar el servidor si es necesario
          # sudo systemctl restart apache2
          EOF
